#==========================================================
#= ProdottiComponent Web Service - Versione Base
#==========================================================
server:
  port: 5052

spring:
  application:
    name: ProdottiWebService
  #==========================================================
  #= PARAMETRI DBMS POSTGRESQL
  #==========================================================
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    password: 123_Stella
    url: jdbc:postgresql://localhost:5435/TestShop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true